name: Deploy Website
on:
    push:
        branches:
            - "main"


 jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v43

            - name: Install and Build
              run: |
                npm ci
                npm run build
              working-directory: ./dbs

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: main
                folder: dbs/build

